In [2]:
import numpy as np
import pandas as pd
import  tpqoa
import time
from datetime import datetime, timedelta, timezone
import warnings
warnings.filterwarnings('ignore')

In [4]:
class ConTrader(tpqoa.tpqoa):
    def __init__(self, conf_file, instrument, bar_length, window, units):
        super().__init__(conf_file)
        self.instrument = instrument
        self.bar_length = pd.to_timedelta(bar_length)
        self.tick_data = pd.DataFrame()
        self.raw_data = None
        self.data = None
        self.last_bar = None
        self.units = units
        self.position = 0
        self.profits = [] # NEW

        #*****************add strategy-specific attributes here******************
        self.window = window
        #************************************************************************

    def get_most_recent(self, days = 5):
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        now = now - timedelta(microseconds = now.microsecond)
        past = now - timedelta(days = days)
        df = self.get_history(instrument = self.instrument, start = past, end = now,
                               granularity = "S5", price = "M", localize = False).c.dropna().to_frame()
        df.rename(columns = {"c":self.instrument}, inplace = True)
        df = df.resample(self.bar_length, label = "right").last().dropna().iloc[:-1]
        self.raw_data = df.copy()
        self.last_bar = self.raw_data.index[-1]

    def on_success(self, time, bid, ask):
        print(self.ticks, end = " ")

        # collect and store tick data
        recent_tick = pd.to_datetime(time)
        df = pd.DataFrame({self.instrument:(ask + bid)/2},
                          index = [recent_tick])
        self.tick_data = pd.concat([self.tick_data, df]) # new with pd.concat()

        # if a time longer than the bar_lenght has elapsed between last full bar and the most recent tick
        if recent_tick - self.last_bar >= self.bar_length:
            self.resample_and_join()
            self. define_strategy()
            self.execute_trades()

    def resample_and_join(self):
        self.raw_data = pd.concat([self.raw_data, self.tick_data.resample(self.bar_length,
                                                                          label="right").last().ffill().iloc[:-1]])
        self.tick_data = self.tick_data.iloc[-1:]
        self.last_bar = self.raw_data.index[-1]

    def define_strategy(self): # "strategy-specific"
        df = self.raw_data.copy()

        #******************** define your strategy here ************************
        df["returns"] = np.log(df[self.instrument] / df[self.instrument].shift(1))
        df["position"] = np.sign(df.returns.rolling(self.window).mean())
        #***********************************************************************

        self.data = df.copy()

    def moving_average(self):
        df = self.raw_data.copy()
        sma_l = 20
        sma_h = 50
        df['SMA_20'] = df[self.instrument].rolling(20).mean()
        df['SMA_50'] = df[self.instrument].rolling(50).mean()
        df['position'] = np.where(df['SMA_20'] > df['SMA_50'], 1, -1)

        self.data = df.copy()

    def execute_trades(self):
        if self.data["position"].iloc[-1] == 1:
            if self.position == 0:
                order = self.create_order(self.instrument, self.units, suppress = True, ret = True)
                self.report_trade(order, "GOING LONG")  # NEW
            elif self.position == -1:
                order = self.create_order(self.instrument, self.units * 2, suppress = True, ret = True)
                self.report_trade(order, "GOING LONG")  # NEW
            self.position = 1
        elif self.data["position"].iloc[-1] == -1:
            if self.position == 0:
                order = self.create_order(self.instrument, -self.units, suppress = True, ret = True)
                self.report_trade(order, "GOING SHORT")  # NEW
            elif self.position == 1:
                order = self.create_order(self.instrument, -self.units * 2, suppress = True, ret = True)
                self.report_trade(order, "GOING SHORT")  # NEW
            self.position = -1
        elif self.data["position"].iloc[-1] == 0:
            if self.position == -1:
                order = self.create_order(self.instrument, self.units, suppress = True, ret = True)
                self.report_trade(order, "GOING NEUTRAL")  # NEW
            elif self.position == 1:
                order = self.create_order(self.instrument, -self.units, suppress = True, ret = True)
                self.report_trade(order, "GOING NEUTRAL")  # NEW
            self.position = 0

    def report_trade(self, order, going):  # NEW
        time = order["time"]
        units = order["units"]
        price = order["price"]
        pl = float(order["pl"])
        self.profits.append(pl)
        cumpl = sum(self.profits)
        print("\n" + 100* "-")
        print("{} | {}".format(time, going))
        print("{} | units = {} | price = {} | P&L = {} | Cum P&L = {}".format(time, units, price, pl, cumpl))
        print(100 * "-" + "\n")

In [18]:
# def moving_average(self):
    #     df = self.raw_data.copy()
    #     sma_l = 20
    #     sma_h = 50
    #     df['SMA_20'] = df[self.instrument].rolling(20).mean()
    #     df['SMA_50'] = df[self.instrument].rolling(50).mean()
    #     df['position'] = np.where(df['SMA_20'] > df['SMA_50'], 1, -1)
    #
    #     self.data = df.copy()

In [7]:
trader = ConTrader('oanda.cfg', 'EUR_USD', bar_length='5s', window=1, units=100000)

In [8]:
trader.get_most_recent()
trader.stream_data(trader.instrument, stop= 200)

if trader.position!= 0:
    close_order= trader.create_order(trader.instrument, units=-trader.position * trader.units, suppress=True, ret=True)
    trader.report_trade(close_order, "GOING NEUTRAL")
    trader.position=0

1 2 3
----------------------------------------------------------------------------------------------------
2026-04-13T19:27:44.947362823Z | GOING LONG
2026-04-13T19:27:44.947362823Z | units = 100000.0 | price = 1.17618 | P&L = 0.0 | Cum P&L = 0.0
----------------------------------------------------------------------------------------------------

4 5 6
----------------------------------------------------------------------------------------------------
2026-04-13T19:27:47.028196254Z | GOING NEUTRAL
2026-04-13T19:27:47.028196254Z | units = -100000.0 | price = 1.17604 | P&L = -14.0 | Cum P&L = -14.0
----------------------------------------------------------------------------------------------------

7 8 9 10
----------------------------------------------------------------------------------------------------
2026-04-13T19:27:50.783162762Z | GOING SHORT
2026-04-13T19:27:50.783162762Z | units = -100000.0 | price = 1.17604 | P&L = 0.0 | Cum P&L = -14.0
----------------------------------------------------------------------------------------------------

11 12 13 14
----------------------------------------------------------------------------------------------------
2026-04-13T19:27:56.303986535Z | GOING LONG
2026-04-13T19:27:56.303986535Z | units = 200000.0 | price = 1.17616 | P&L = -12.0 | Cum P&L = -26.0
----------------------------------------------------------------------------------------------------

15 16 17 18 19
----------------------------------------------------------------------------------------------------
2026-04-13T19:28:02.485140810Z | GOING SHORT
2026-04-13T19:28:02.485140810Z | units = -200000.0 | price = 1.17604 | P&L = -12.0 | Cum P&L = -38.0
----------------------------------------------------------------------------------------------------

20 21 22 23 24 25 26 27
----------------------------------------------------------------------------------------------------
2026-04-13T19:28:24.702932463Z | GOING NEUTRAL
2026-04-13T19:28:24.702932463Z | units = 100000.0 | price = 1.17616 | P&L = -12.0 | Cum P&L = -50.0
----------------------------------------------------------------------------------------------------

28 29 30
----------------------------------------------------------------------------------------------------
2026-04-13T19:28:30.326354155Z | GOING LONG
2026-04-13T19:28:30.326354155Z | units = 100000.0 | price = 1.17616 | P&L = 0.0 | Cum P&L = -50.0
----------------------------------------------------------------------------------------------------

31
----------------------------------------------------------------------------------------------------
2026-04-13T19:28:30.895223168Z | GOING NEUTRAL
2026-04-13T19:28:30.895223168Z | units = -100000.0 | price = 1.17605 | P&L = -11.0 | Cum P&L = -61.0
----------------------------------------------------------------------------------------------------

32 33 34 35 36 37 38 39
----------------------------------------------------------------------------------------------------
2026-04-13T19:28:52.960512785Z | GOING SHORT
2026-04-13T19:28:52.960512785Z | units = -100000.0 | price = 1.17597 | P&L = 0.0 | Cum P&L = -61.0
----------------------------------------------------------------------------------------------------

40 41 42 43 44
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:03.490936294Z | GOING NEUTRAL
2026-04-13T19:29:03.490936294Z | units = 100000.0 | price = 1.17606 | P&L = -9.0 | Cum P&L = -70.0
----------------------------------------------------------------------------------------------------

45 46
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:09.358092080Z | GOING SHORT
2026-04-13T19:29:09.358092080Z | units = -100000.0 | price = 1.17596 | P&L = 0.0 | Cum P&L = -70.0
----------------------------------------------------------------------------------------------------

47 48
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:15.519943516Z | GOING NEUTRAL
2026-04-13T19:29:15.519943516Z | units = 100000.0 | price = 1.17606 | P&L = -10.0 | Cum P&L = -80.0
----------------------------------------------------------------------------------------------------

49 50 51 52 53
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:42.210945970Z | GOING LONG
2026-04-13T19:29:42.210945970Z | units = 100000.0 | price = 1.17611 | P&L = 0.0 | Cum P&L = -80.0
----------------------------------------------------------------------------------------------------

54 55 56 57 58 59
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:47.686465474Z | GOING SHORT
2026-04-13T19:29:47.686465474Z | units = -200000.0 | price = 1.176 | P&L = -11.0 | Cum P&L = -91.0
----------------------------------------------------------------------------------------------------

60 61
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:53.175981317Z | GOING NEUTRAL
2026-04-13T19:29:53.175981317Z | units = 100000.0 | price = 1.17611 | P&L = -11.0 | Cum P&L = -102.0
----------------------------------------------------------------------------------------------------

62 63 64
----------------------------------------------------------------------------------------------------
2026-04-13T19:29:55.453569860Z | GOING SHORT
2026-04-13T19:29:55.453569860Z | units = -100000.0 | price = 1.176 | P&L = 0.0 | Cum P&L = -102.0
----------------------------------------------------------------------------------------------------

65 66 67 68
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:03.315278836Z | GOING LONG
2026-04-13T19:30:03.315278836Z | units = 200000.0 | price = 1.17615 | P&L = -15.0 | Cum P&L = -117.0
----------------------------------------------------------------------------------------------------

69 70 71 72 73 74 75 76 77 78 79
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:20.330214165Z | GOING NEUTRAL
2026-04-13T19:30:20.330214165Z | units = -100000.0 | price = 1.17595 | P&L = -20.0 | Cum P&L = -137.0
----------------------------------------------------------------------------------------------------

80 81
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:22.300534716Z | GOING SHORT
2026-04-13T19:30:22.300534716Z | units = -100000.0 | price = 1.17595 | P&L = 0.0 | Cum P&L = -137.0
----------------------------------------------------------------------------------------------------

82 83 84 85
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:30.893904805Z | GOING LONG
2026-04-13T19:30:30.893904805Z | units = 200000.0 | price = 1.17608 | P&L = -13.0 | Cum P&L = -150.0
----------------------------------------------------------------------------------------------------

86 87 88 89
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:36.928859873Z | GOING SHORT
2026-04-13T19:30:36.928859873Z | units = -200000.0 | price = 1.17596 | P&L = -12.0 | Cum P&L = -162.0
----------------------------------------------------------------------------------------------------

90 91 92 93 94 95 96 97
----------------------------------------------------------------------------------------------------
2026-04-13T19:30:46.734154376Z | GOING LONG
2026-04-13T19:30:46.734154376Z | units = 200000.0 | price = 1.17609 | P&L = -13.0 | Cum P&L = -175.0
----------------------------------------------------------------------------------------------------

98 99 100 101 102 103 104 105

V20Timeout: v20 REST request to https://stream-fxpractice.oanda.com:443/v3/accounts/101-011-37974904-002/pricing/stream?instruments=EUR_USD&snapshot=True has timed out (stream)

In [15]:
trader.data

In [16]:
trader.tick_data

Empty DataFrame
Columns: []
Index: []

In [3]:
api = tpqoa.tpqoa('oanda.cfg')

In [ ]:
api.stream_data()

In [9]:
data = api.get_history('EUR_USD', "2026-01-01", "2026-04-01", "H4", "M")

In [10]:
data

                           o        h        l        c  volume  complete
time
2026-01-01 22:00:00  1.17498  1.17628  1.17458  1.17610    6047      True
2026-01-02 02:00:00  1.17610  1.17650  1.17508  1.17513    6240      True
2026-01-02 06:00:00  1.17512  1.17516  1.17206  1.17214   20335      True
2026-01-02 10:00:00  1.17214  1.17290  1.17132  1.17215   19041      True
2026-01-02 14:00:00  1.17217  1.17545  1.17158  1.17308   27370      True
...                      ...      ...      ...      ...     ...       ...
2026-03-31 05:00:00  1.14692  1.14758  1.14608  1.14672   25715      True
2026-03-31 09:00:00  1.14672  1.15099  1.14576  1.15030   39112      True
2026-03-31 13:00:00  1.15031  1.15598  1.15006  1.15404   81234      True
2026-03-31 17:00:00  1.15404  1.15634  1.15384  1.15532   43814      True
2026-03-31 21:00:00  1.15540  1.15790  1.15528  1.15745   11651      True

[379 rows x 6 columns]