In [1]:
import numpy as np
import tpqoa
from src.DatasetStructure import DatasetStructure
from src.Structures import Structures
from src.StatTest import StatTest

In [2]:
api = tpqoa.tpqoa('oanda.cfg')

In [7]:
api.get_instruments()

[('AUD/CAD', 'AUD_CAD'),
 ('AUD/CHF', 'AUD_CHF'),
 ('AUD/HKD', 'AUD_HKD'),
 ('AUD/JPY', 'AUD_JPY'),
 ('AUD/NZD', 'AUD_NZD'),
 ('AUD/SGD', 'AUD_SGD'),
 ('AUD/USD', 'AUD_USD'),
 ('Australia 200', 'AU200_AUD'),
 ('Bitcoin', 'BTC_USD'),
 ('Bitcoin Cash', 'BCH_USD'),
 ('Brent Crude Oil', 'BCO_USD'),
 ('Bund', 'DE10YB_EUR'),
 ('CAD/CHF', 'CAD_CHF'),
 ('CAD/HKD', 'CAD_HKD'),
 ('CAD/JPY', 'CAD_JPY'),
 ('CAD/SGD', 'CAD_SGD'),
 ('CHF/HKD', 'CHF_HKD'),
 ('CHF/JPY', 'CHF_JPY'),
 ('CHF/ZAR', 'CHF_ZAR'),
 ('China A50', 'CN50_USD'),
 ('China H Shares', 'CHINAH_HKD'),
 ('Copper', 'XCU_USD'),
 ('Corn', 'CORN_USD'),
 ('EUR/AUD', 'EUR_AUD'),
 ('EUR/CAD', 'EUR_CAD'),
 ('EUR/CHF', 'EUR_CHF'),
 ('EUR/CZK', 'EUR_CZK'),
 ('EUR/DKK', 'EUR_DKK'),
 ('EUR/GBP', 'EUR_GBP'),
 ('EUR/HKD', 'EUR_HKD'),
 ('EUR/HUF', 'EUR_HUF'),
 ('EUR/JPY', 'EUR_JPY'),
 ('EUR/NOK', 'EUR_NOK'),
 ('EUR/NZD', 'EUR_NZD'),
 ('EUR/PLN', 'EUR_PLN'),
 ('EUR/SEK', 'EUR_SEK'),
 ('EUR/SGD', 'EUR_SGD'),
 ('EUR/TRY', 'EUR_TRY'),
 ('EUR/USD', 'EUR_USD'),
 ('EUR/ZAR', 'EUR_ZAR'),
 ('Ether', 'ETH_USD'),
 ('Europe 50', 'EU50_EUR'),
 ('France 40', 'FR40_EUR'),
 ('GBP/AUD', 'GBP_AUD'),
 ('GBP/CAD', 'GBP_CAD'),
 ('GBP/CHF', 'GBP_CHF'),
 ('GBP/HKD', 'GBP_HKD'),
 ('GBP/JPY', 'GBP_JPY'),
 ('GBP/NZD', 'GBP_NZD'),
 ('GBP/PLN', 'GBP_PLN'),
 ('GBP/SGD', 'GBP_SGD'),
 ('GBP/USD', 'GBP_USD'),
 ('GBP/ZAR', 'GBP_ZAR'),
 ('Germany 30', 'DE30_EUR'),
 ('Gold', 'XAU_USD'),
 ('Gold/AUD', 'XAU_AUD'),
 ('Gold/CAD', 'XAU_CAD'),
 ('Gold/CHF', 'XAU_CHF'),
 ('Gold/EUR', 'XAU_EUR'),
 ('Gold/GBP', 'XAU_GBP'),
 ('Gold/HKD', 'XAU_HKD'),
 ('Gold/JPY', 'XAU_JPY'),
 ('Gold/NZD', 'XAU_NZD'),
 ('Gold/SGD', 'XAU_SGD'),
 ('Gold/Silver', 'XAU_XAG'),
 ('HKD/JPY', 'HKD_JPY'),
 ('Hong Kong 33', 'HK33_HKD'),
 ('Japan 225', 'JP225_USD'),
 ('Japan 225 (JPY)', 'JP225Y_JPY'),
 ('Litecoin', 'LTC_USD'),
 ('NZD/CAD', 'NZD_CAD'),
 ('NZD/CHF', 'NZD_CHF'),
 ('NZD/HKD', 'NZD_HKD'),
 ('NZD/JPY', 'NZD_JPY'),
 ('NZD/SGD', 'NZD_SGD'),
 ('NZD/USD', 'NZD_USD'),
 ('Natural Gas', 'NATGAS_USD'),
 ('Netherlands 25', 'NL25_EUR'),
 ('Palladium', 'XPD_USD'),
 ('Platinum', 'XPT_USD'),
 ('SGD/CHF', 'SGD_CHF'),
 ('SGD/JPY', 'SGD_JPY'),
 ('Silver', 'XAG_USD'),
 ('Silver/AUD', 'XAG_AUD'),
 ('Silver/CAD', 'XAG_CAD'),
 ('Silver/CHF', 'XAG_CHF'),
 ('Silver/EUR', 'XAG_EUR'),
 ('Silver/GBP', 'XAG_GBP'),
 ('Silver/HKD', 'XAG_HKD'),
 ('Silver/JPY', 'XAG_JPY'),
 ('Silver/NZD', 'XAG_NZD'),
 ('Silver/SGD', 'XAG_SGD'),
 ('Singapore 30', 'SG30_SGD'),
 ('Soybeans', 'SOYBN_USD'),
 ('Spain 35', 'ESPIX_EUR'),
 ('Sugar', 'SUGAR_USD'),
 ('Switzerland 20', 'CH20_CHF'),
 ('TRY/JPY', 'TRY_JPY'),
 ('UK 100', 'UK100_GBP'),
 ('UK 10Y Gilt', 'UK10YB_GBP'),
 ('US 10Y T-Note', 'USB10Y_USD'),
 ('US 2Y T-Note', 'USB02Y_USD'),
 ('US 5Y T-Note', 'USB05Y_USD'),
 ('US Nas 100', 'NAS100_USD'),
 ('US Russ 2000', 'US2000_USD'),
 ('US SPX 500', 'SPX500_USD'),
 ('US T-Bond', 'USB30Y_USD'),
 ('US Wall St 30', 'US30_USD'),
 ('USD/CAD', 'USD_CAD'),
 ('USD/CHF', 'USD_CHF'),
 ('USD/CNH', 'USD_CNH'),
 ('USD/CZK', 'USD_CZK'),
 ('USD/DKK', 'USD_DKK'),
 ('USD/HKD', 'USD_HKD'),
 ('USD/HUF', 'USD_HUF'),
 ('USD/JPY', 'USD_JPY'),
 ('USD/MXN', 'USD_MXN'),
 ('USD/NOK', 'USD_NOK'),
 ('USD/PLN', 'USD_PLN'),
 ('USD/SEK', 'USD_SEK'),
 ('USD/SGD', 'USD_SGD'),
 ('USD/THB', 'USD_THB'),
 ('USD/TRY', 'USD_TRY'),
 ('USD/ZAR', 'USD_ZAR'),
 ('West Texas Oil', 'WTICO_USD'),
 ('Wheat', 'WHEAT_USD'),
 ('ZAR/JPY', 'ZAR_JPY')]

In [8]:
df = api.get_history('BTC_USD', '2020-01-01 00:00', '2025-12-30 23:00', 'H1', 'B')

In [9]:
df.tail()

                           o        h        l        c  volume  complete
time
2025-12-30 18:00:00  88282.0  88410.0  88024.0  88207.0    3131      True
2025-12-30 19:00:00  88211.0  88340.0  87861.0  88136.0    3239      True
2025-12-30 20:00:00  88129.0  88136.0  87763.0  87814.0    2980      True
2025-12-30 21:00:00  87821.0  88239.0  87768.0  88171.0    2288      True
2025-12-30 22:00:00  88276.1  88370.0  88139.0  88320.0    1865      True

In [18]:
df.to_csv('BTC_1H.csv')

In [2]:
datastructure = DatasetStructure('Dataset/BTC_1H.csv')

In [3]:
datastructure.ATR(14)

In [4]:
datastructure.vol_regime()

In [8]:
datastructure.time_control()

In [9]:
data = datastructure.show_data()

In [10]:
structure = Structures(data)

In [11]:
bullish_ob = structure.analyze_gold_obs('bullish')

In [12]:
bullish_ob.tail()

,Type,Created_At,time,vol_regime,sessions,Hit_At,Return,Zone_Top,Zone_Bottom
116,Bullish,2025-08-06 05:00:00,2025-08-19 15:00:00,Medium,london/NY,2025-08-19 15:00:00,-0.007027,113575.7,113330.2
117,Bullish,2025-09-11 03:00:00,2025-09-11 14:00:00,Medium,london/NY,2025-09-11 14:00:00,0.012202,113974.7,113723.0
118,Bullish,2025-06-23 22:00:00,2025-10-17 10:00:00,High,london,2025-10-17 10:00:00,0.022017,104262.0,103676.4
119,Bullish,2025-05-06 22:00:00,2025-11-14 12:00:00,High,london,2025-11-14 12:00:00,-0.012197,94786.8,94376.8
120,Bullish,2025-04-22 21:00:00,2025-11-17 20:00:00,High,NY,2025-11-17 20:00:00,-0.025409,91571.4,91130.4

In [13]:
bullish_ob['Return'].mean()

np.float64(-0.002492264003406907)

In [16]:
bullish_ob['Return'].std()

np.float64(0.025092562362531518)

In [17]:
bearish_ob = structure.analyze_gold_obs('bearish')
bearish_ob.tail()

,Type,Created_At,time,vol_regime,sessions,Hit_At,Return,Zone_Top,Zone_Bottom
114,Bearish,2025-09-19 09:00:00,2025-10-01 12:00:00,Medium,london,2025-10-01 12:00:00,0.011757,117136.0,116914.0
115,Bearish,2025-08-14 12:00:00,2025-10-02 18:00:00,High,NY,2025-10-02 18:00:00,-0.003939,121066.5,120719.5
116,Bearish,2025-11-03 15:00:00,2025-11-11 01:00:00,Medium,asian,2025-11-11 01:00:00,-0.007344,108287.6,107328.9
117,Bearish,2025-11-11 12:00:00,2025-11-12 11:00:00,Low,london,2025-11-12 11:00:00,-0.029913,105490.0,105115.0
118,Bearish,2025-11-23 23:00:00,2025-11-24 16:00:00,Medium,london/NY,2025-11-24 16:00:00,0.008481,87995.0,87505.0

In [21]:
bearish_ob.to_csv('bearish_ob.csv')

In [22]:
bullish_ob.to_csv('bullish_ob.csv')

In [18]:
bearish_ob['Return'].mean()

np.float64(0.0005300549920794842)

In [19]:
events = bullish_ob.copy()

events['failed'] = events['Return'] <= 0

failure_rate = events['failed'].mean()
print(failure_rate)

0.5537190082644629

In [20]:
events = bearish_ob.copy()

events['failed'] = events['Return'] <= 0

failure_rate = events['failed'].mean()
print(failure_rate)

0.5042016806722689

In [ ]:
events.groupby('vol_regime')['failed'].mean()
events.groupby('sessions')['failed'].mean()

events.groupby('year')['failed'].mean()
events[events['year'] == 2017][events['vol_regime'] == 'High']['Return'].mean()
df[df['vol_regime'] == 'High'][df['year'] == 2025]['forward_return_10bar'].mean()